### ISSUE TITLE
Please make available for Emacs 25.1

### ISSUE THREAD

**Issue by rrthomas** [PythonNut/helm-flx#19] opened 2016-10-21 19:42 UTC
This package requires Emacs 24.4. I presume that's why it doesn't show up for me on Emacs 25.1 on MELPA?

**Comment by nickserv** [comment] 2016-12-07 19:34
I'm using Emacs 25.1 and I see it on MELPA. Is your issue fixed, or are you perhaps missing it from MELPA stable?

**Comment by rrthomas** [comment] 2016-12-07 21:22
You've got it, I meant MELPA stable.

**Comment by nickserv** [comment] 2016-12-07 21:40
Ah okay, this seems like a duplicate of #18 then. You might be able to get around this by adding both normal and stable MELPA to your package archive list, giving a higher priority to stable for other packages.

**Comment by rrthomas** [comment] 2016-12-07 21:57
Yes, it is (I didn't realise at first, I thought it might be a version-compatibility thing). I have used the fix you suggested, and it's working; thanks.

**Comment by PythonNut** [comment] 2016-12-09 22:03
See the resolution to #18.

**Closed as completed by PythonNut** 2016-12-09 22:03 UTC
